"""
Backend API Endpoint Example for Gene Perturbation Signatures

This file provides example code for the backend API endpoint that serves
gene perturbation signature data. Add this to your FastAPI backend.

The endpoint expects pre-computed signature scores stored in parquet files
(generated by calculate_signature_scores.py).
"""

import json
import os
from typing import Dict, List, Optional

import pandas as pd
import pyarrow.parquet as pq
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

# Router for perturbation signatures
router = APIRouter(prefix="/api/v1/perturbation-signatures", tags=["perturbation-signatures"])


class SignatureRequest(BaseModel):
    """Request model for signature scores"""
    genes: List[str]  # List of perturbed genes to query
    cell_lines: Optional[List[str]] = None  # Optional filter by cell lines
    signatures: Optional[List[str]] = None  # Optional filter by signatures


class SignatureResponse(BaseModel):
    """Response model for signature scores"""
    data: Dict  # Nested dict: gene -> signature -> cell_line -> score
    genes: List[str]
    signatures: List[str]
    cell_lines: List[str]
    heatmap_data: Dict  # Data formatted for heatmap visualization


# Global cache for signature data
_signature_cache: Optional[pd.DataFrame] = None
_data_path = os.environ.get("SIGNATURE_DATA_PATH", "./data/signature_scores.parquet")


def load_signature_data() -> pd.DataFrame:
    """Load signature scores from parquet file with caching."""
    global _signature_cache

    if _signature_cache is not None:
        return _signature_cache

    if not os.path.exists(_data_path):
        raise HTTPException(
            status_code=500,
            detail=f"Signature data file not found: {_data_path}"
        )

    _signature_cache = pd.read_parquet(_data_path)
    return _signature_cache


def get_available_signatures() -> List[str]:
    """Get list of available signatures."""
    df = load_signature_data()
    return [col for col in df.columns if col != 'cell_line']


def get_available_cell_lines() -> List[str]:
    """Get list of available cell lines."""
    df = load_signature_data()
    return df['cell_line'].unique().tolist()


def get_available_genes() -> List[str]:
    """Get list of available perturbed genes."""
    df = load_signature_data()
    return df.index.unique().tolist()


@router.get("/signatures")
async def list_signatures():
    """List all available gene signatures."""
    return {"signatures": get_available_signatures()}


@router.get("/cell-lines")
async def list_cell_lines():
    """List all available cell lines."""
    return {"cell_lines": get_available_cell_lines()}


@router.get("/genes")
async def list_genes():
    """List all available perturbed genes."""
    return {"genes": get_available_genes()}


@router.post("/query")
async def query_signatures(request: SignatureRequest) -> SignatureResponse:
    """
    Query signature scores for specific genes.

    Returns scores for each gene-signature-cell_line combination,
    formatted for both table and heatmap visualization.
    """
    df = load_signature_data()

    # Normalize gene names to uppercase
    query_genes = [g.upper() for g in request.genes]

    # Filter by genes
    available_genes = [g for g in query_genes if g in df.index]
    if not available_genes:
        raise HTTPException(
            status_code=404,
            detail=f"None of the requested genes found. Available genes: {df.index[:10].tolist()}..."
        )

    result_df = df.loc[available_genes].copy()

    # Filter by cell lines if specified
    if request.cell_lines:
        result_df = result_df[result_df['cell_line'].isin(request.cell_lines)]

    # Get signature columns
    signature_cols = [col for col in result_df.columns if col != 'cell_line']

    # Filter by signatures if specified
    if request.signatures:
        signature_cols = [s for s in request.signatures if s in signature_cols]
        if not signature_cols:
            raise HTTPException(
                status_code=404,
                detail="None of the requested signatures found"
            )

    # Build response data
    result_data = {}
    for gene in result_df.index.unique():
        gene_data = result_df.loc[[gene]]
        result_data[gene] = {}
        for sig in signature_cols:
            result_data[gene][sig] = {}
            for _, row in gene_data.iterrows():
                cell_line = row['cell_line']
                score = row[sig]
                if pd.notna(score):
                    result_data[gene][sig][cell_line] = float(score)

    # Build heatmap data format
    # Format: { rows: genes, columns: signatures, values: [[score, ...], ...], cell_line: str }
    cell_lines = result_df['cell_line'].unique().tolist()
    heatmap_data = {}

    for cell_line in cell_lines:
        cell_df = result_df[result_df['cell_line'] == cell_line]
        values = []
        genes_list = cell_df.index.tolist()

        for gene in genes_list:
            row_values = cell_df.loc[gene, signature_cols].tolist()
            values.append([float(v) if pd.notna(v) else None for v in row_values])

        heatmap_data[cell_line] = {
            "rows": genes_list,
            "columns": signature_cols,
            "values": values
        }

    return SignatureResponse(
        data=result_data,
        genes=available_genes,
        signatures=signature_cols,
        cell_lines=cell_lines,
        heatmap_data=heatmap_data
    )


@router.post("/heatmap")
async def get_heatmap_data(request: SignatureRequest):
    """
    Get data specifically formatted for InchLib heatmap visualization.

    Returns data in the format expected by the InchLib library.
    """
    df = load_signature_data()

    # Normalize gene names
    query_genes = [g.upper() for g in request.genes]
    available_genes = [g for g in query_genes if g in df.index]

    if not available_genes:
        raise HTTPException(status_code=404, detail="No matching genes found")

    result_df = df.loc[available_genes].copy()

    # Filter by cell lines
    if request.cell_lines:
        result_df = result_df[result_df['cell_line'].isin(request.cell_lines)]

    # Get signature columns
    signature_cols = [col for col in result_df.columns if col != 'cell_line']
    if request.signatures:
        signature_cols = [s for s in request.signatures if s in signature_cols]

    cell_lines = result_df['cell_line'].unique().tolist()
    inchlib_data = {}

    for cell_line in cell_lines:
        cell_df = result_df[result_df['cell_line'] == cell_line][signature_cols]

        # Build InchLib format
        nodes = {}
        for idx, (gene, row) in enumerate(cell_df.iterrows()):
            nodes[str(idx)] = {
                "count": 1,
                "objects": [gene],
                "features": row.tolist()
            }

        inchlib_data[cell_line] = {
            "data": {
                "nodes": nodes,
                "feature_names": signature_cols
            }
        }

    return inchlib_data


# Legacy endpoint for compatibility with existing getData pattern
async def handle_perturbation_signature_request(body: dict) -> dict:
    """
    Handler for legacy /getData endpoint.

    This function should be called from your main getData handler
    when request type is "perturbationSignatures".
    """
    genes = body.get("genes", "").split(";")
    genes = [g.strip().upper() for g in genes if g.strip()]

    cell_lines = body.get("cell_lines")
    if cell_lines and isinstance(cell_lines, str):
        cell_lines = [c.strip() for c in cell_lines.split(";") if c.strip()]

    signatures = body.get("signatures")
    if signatures and isinstance(signatures, str):
        signatures = [s.strip() for s in signatures.split(";") if s.strip()]

    request = SignatureRequest(
        genes=genes,
        cell_lines=cell_lines,
        signatures=signatures
    )

    try:
        response = await query_signatures(request)
        return {
            "status": "SUCCESS",
            "result": response.dict()
        }
    except HTTPException as e:
        return {
            "status": "FAILURE",
            "error": e.detail
        }


# Example of how to integrate with existing /getData endpoint:
"""
# In your main API file, add to the request handler:

from perturbation_signatures import handle_perturbation_signature_request

@app.post("/getData")
async def get_data(request: Request):
    body = await request.json()
    request_type = body.get("request")

    if request_type == "perturbationSignatures":
        return await handle_perturbation_signature_request(body)

    # ... existing handlers ...
"""
